blog/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

# post_list = views.PostViewSet.as_view({
#         'get':'list',
#         'post': 'create'
#     })

# post_detail = views.PostViewSet.as_view({
#         'get':'retrive',
#         'put':'update',
#         'patch':'partial_update',
#         'delete':'destroy'

#     })

# user_list = views.UserViewSet.as_view({
#         'get':'list'
#     })

# user_detail = views.UserViewSet.as_view({
#         'get': 'retrive'
#     })

urlpatterns = format_suffix_patterns([

    url(r'^post/$',views.PostListView.as_view(),name='post-list'),
    url(r'^post/create/$',views.PostCreateView.as_view(),name='post-create'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$',views.PostEditView.as_view(),name='post-edit'),
    url(r'^post/(?P<pk>[0-9]+)/delete/$',views.PostDeleteView.as_view(),name='post-delete'),
    url(r'^comment/$', views.CommentListView.as_view() ,name='comment-list'),
    url(r'^comment/create/$',views.CommentCreateView.as_view(),name='comment-create'),
    url(r'^comment/(?P<pk>[0-9]+)/detail/$', views.CommentDetailView.as_view() ,name='comment-detail'),
    url(r'^comment/(?P<post_id>[0-9]+)/post_comments/$', views.CommentListView.as_view(), name='post-comment-list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post-detail'),
    url(r'^(?P<pk>[0-9]+)/status_update/$', views.PostStatusUpdate.as_view(), name='post-status-update'),
    
])

blog/urls.py
from django.conf.urls import url, include
from . import views



urlpatterns = [

    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/detail/$', views.PostDetailView.as_view(), name='post_detail'),
    # url(r'^like/$',views.post_like, name='like'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/del/$',views.PostDeleteView.as_view(),name='del_blog'),
    # url(r'^post/search_post/$', views.BlogSearchListView.as_view(), name='search_post'),
    # url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/new/$', views.PostCreateView.as_view(), name='post_new'),
    # url(r'^post/(?P<pk>\d+)/detail/$',views.post_detail, name='post_detail'),
    # url(r'^post/(?P<pk>\d+)/edit/$',views.post_edit,name='post_edit'),
    # url(r'^post/(?P<pk>\d+)/del/$',views.del_blog,name='del_blog'),
    url(r'^password/$', views.change_password, name='change_password'),
    # url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post_title/$',views.search_post_title, name = 'post_title'),  
    
    url(r'^(?P<pk>[\d]+)/like/$', views.PostLikeToggle.as_view(), name='like-toggle'),
    url(r'^api/(?P<pk>[\d]+)/like/$', views.PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    url(r'^request/$',views.WriterRequestForm.as_view(),name='writer_request'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog import views
from accounts import views as accounts_views
from django.views.generic import TemplateView
from tastypie.api import Api
from blog.api import views as blog_views
from rest_framework.routers import DefaultRouter

# from blog.api import AjaxSearchResource
# router = DefaultRouter()
# router.register(r'post', PostViewSet)
# router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^login/$',auth_views.login,name='login'),
    url(r'^logout/$',auth_views.logout,name='logout'),
    # url(r'^signup/$',views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='posts')),
    url(r'^profiles/',include('accounts.urls',namespace='profiles')),
    # url(r'^api/',include(rest_api.urls)),
    url(r'^api/$', blog_views.api_root),
    url(r'^api/post/',include('blog.api.urls')),
    url(r'^api/users/',include('accounts.api.urls',namespace='api-users')),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^rest-auth/', include('rest_auth.urls',namespace='rest')),
    # url(r"^likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    # url(r'^auth/', include('rest_framework_social_oauth2.urls')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^about/$', views.AboutView.as_view(),name='about_us'),
    # url(r'^posts-api/', include(router.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls',namespace='pages')),
    url(r'^contact/$', views.ContactView.as_view(),name='contact'),
    url(r'^signup/$',accounts_views.signup, name='signup'),
    url(r'^ajax/validate_username/$',accounts_views.validate_username, name='validate_username'),
    url(r'^profile/$',accounts_views.MyProfileView.as_view(),name='my_profile'),
    url(r'^reset/$',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ),
    name='password_reset'),
    url(r'^reset/done/$',
    auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
    name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
    name='password_reset_confirm'),
    url(r'^reset/complete/$',
    auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    name='password_reset_complete'),

    url(r'^account_activation_sent/$', accounts_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        accounts_views.activate, name='activate'),


]

urlpatterns += [
    
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from .managers import PostManager, CommentManager
from django.conf import settings
import datetime

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    views = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    created_date = models.DateTimeField(default =timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    approved = models.BooleanField(default= False)
    updated_date = models.DateTimeField( default =timezone.now)

    objects = PostManager()

    class Meta:
        ordering = ['-published_date']

    def publish():
        self.published_date = datetime.datetime.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('posts:post_detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

    @property
    def get_comment(self):
        instance = self
        qs = Comment.objects.filter(post=instance)
        return qs

    def get_like_url(self):
        return reverse('posts:like-toggle', kwargs={"pk": self.pk})

    def get_api_like_url(self):
        return reverse('posts:like-api-toggle', kwargs={"pk": self.pk})



class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.ForeignKey('auth.user')
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,related_name='replies')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    objects = CommentManager()

    class Meta:
        ordering = ['-created_date']

    def approve(self):
        self.approved_comment = True
        self.save()

    def has_replies(self):
        return Comment.objects.filter(parent=self)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','text')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'Post Title'}),            
        }

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text',)
        widgets ={
            'text': forms.Textarea(attrs={'rows':1, 'placeholder':'Write your thoughts about post.'}),
        }


class ContactForm(forms.Form):
    name = forms.CharField(max_length=120, widget=forms.TextInput(attrs={'placeholder':'Enter name',}))
    subject = forms.CharField(max_length=120, widget=forms.TextInput(attrs={'placeholder':'Enter subject for future reference.',}))
    email = forms.CharField(max_length=120, widget=forms.EmailInput(attrs={'placeholder':'Enter valid email id. eg. abc@gmail.com',}))
    message = forms.CharField(widget = forms.Textarea(attrs={'placeholder':'what is in your mind ?',}))
    
class RequestForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Write Your Message Here',}))    

blog/api/views.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import Http404
from django.contrib.auth.models import User
import datetime

from rest_framework import status, mixins, generics, permissions, viewsets, renderers
from rest_framework.response import Response
from rest_framework.decorators import api_view, detail_route
from rest_framework.views import APIView
from rest_framework.reverse import reverse
from django.db.models import Q
from blog.models import Post, Comment
from .serializers import (PostSerializer, UserSerializer, PostListSerializer, 
                            PostDetailSerializer, CommentSerializer, CommentDetailSerialzer, 
                            PostCreateSerializer, PostEditSerializer, PostDeleteSerializer,
                            CommentCreateSerializer,PostStatusUpdateSerializer )
from .permissions import IsAutherReadOnly

@api_view(['GET'])
def api_root(request,format=None):
    return Response({
        'user': reverse('api-users:user-list', request= request, format=format),
        'post': reverse('post-list', request=request, format=format),
        'comment': reverse('comment-list', request=request, format=format)
    })


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsAutherReadOnly)

    # @detail_route(renderer_classes=[renderers.StaticHTMLRenderer])
    def perform_create(self, serializer):
        serializer.save(author= self.request.user)    

class CommentListView(generics.ListAPIView):
    model = Comment
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsAutherReadOnly)

    def get_queryset(self):
        queryset = Comment.objects.filter(parent=None)
        try:
           post_id =self.kwargs['post_id']
           if post_id is not None:
                queryset = Comment.objects.filter(
                   Q(parent=None),
                   Q(post=post_id)
                   )
                return queryset
        except:
            pass
        return queryset
 
class CommentRepliesListAPIView(generics.ListAPIView):
   serializer_class = CommentSerializer
 
   def get_queryset(self):
       queryset = Comment.objects.filter(parent!=None)
       return queryset

class CommentDetailView(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentDetailSerialzer
    permissions_class = (permissions.IsAuthenticatedOrReadOnly,IsAutherReadOnly)

class CommentCreateView(generics.CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentCreateSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsAutherReadOnly)

    def perform_create(self, serializer):
        serializer.save(author= self.request.user)
        serializer.save(published_date= datetime.datetime.now())

class PostListView(generics.ListAPIView):
    model = Post
    serializer_class = PostListSerializer
    Permission_classes = (permissions.AllowAny,)

    def get_queryset(self):
        queryset = Post.objects.all()
        query = self.request.query_params.get('q',None)
        if query is not None:
            queryset = Post.objects.search(query)
        return queryset

class PostDetailView(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    Permission_classes = (permissions.AllowAny,)

class PostCreateView(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def perform_create(self, serializer):
        serializer.save(author= self.request.user)
        serializer.save(published_date= datetime.datetime.now())

class PostEditView(generics.RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostEditSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def perform_edit(self, serializer):
        serializer.save(author= self.request.user)
        serializer.save(published_date= datetime.datetime.now())

class PostDeleteView(generics.RetrieveDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDeleteSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class PostStatusUpdate(generics.RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostStatusUpdateSerializer
    permission_classes = (permissions.IsAuthenticated,)

    

blog/templates/blog/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
            <h1>New comment</h1>
        <form method="POST" class="post-form">
            {% csrf_token %}
            {% include 'includes/form_snippet.html' %}
            <button type="submit" class="save btn btn-info">Send</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/change_password.html
{% extends 'base.html' %}

    {% block content %}
    <div class="container-fluid">
        <form method="post">
            <h2> Change Password</h2>
          {% csrf_token %}
          {% include 'includes/form_snippet.html'%}
          <button type="submit" class="btn btn-success">Change Password</button>
        </form>
    </div>
     {% endblock %}

blog/templates/blog/conferm_del.html
{% extends 'base.html' %}

{% block content %}
<h3>Delete Post</h3>
    <div class="container" style="padding-top: 50px;">
    <form action="" method="post">{% csrf_token %}
        <h3>Are you sure you want to delete "<a href="{% url 'posts:post_detail' pk=post.pk %}" >{{ object }}</a>"?</h3>
        <p></p>
        <button type="submit" class="btn btn-danger"> Confirm </button>
    </form>
    </div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}


    {% block content %}
    {% if messages %}
        {% for messages in messages %}
        <div class="alert alert-danger " role="alert">    
            <strong>{{ messages }}</strong>  {{ post.title }}
        </div>
        {% endfor %}
    {% endif %}
    <div class="container-fluied">
    <div class="row">
    <div class  ="col-md-8">
    <h1> Blog Posts</h1>  
    {% for post in posts[:5] %}
        <div class="card card-outline-primary" style="height: 130pt;" >
          <div class="card-header" style="height: 55pt;" >
                <h5 class="card-title"><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title|upper }}</a></h5> 
                <p><b>Pub On :</b> {{post.published_date }} <b>By :</b> {{ post.author }} <b>Comments :</b> {{ post.comments.count }} <b>Views :</b> {{ post.views }} </p> 
          </div>
          <div class="card-block" style="height: 75pt;">
              <p class="card-text" >{{ post.text|truncatewords:10}}<a href="{% url 'post_detail' pk=post.pk %}" >Read more</a></p>
                <a class="card-link " href="{% url 'post_edit' pk=post.pk %}">Edit
                <a href="{% url 'del_blog' pk=post.pk %}" class="card-link">Delete</a>
              <a href="" class="card-link"><span class="glyphicon glyphicon-thumbs-up"></span></a></a>
          </div>
        </div>
    {% empty %}
      <strong>No posts found!</strong>
    {% endfor %}

    {% include 'includes/pagination.html' %}
    </div>
    <div class="col-md-4">
    <div class="card card-outline-primary" style="height: 150pt;" >
      <div class="card-header" style="height: 35pt;" >Top Commented</div>    
      <div class="card-block" style="height: 80pt;">
           <ul>
              {% for post in most_commented %}
                <li><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></li>
              {% endfor %}
           </ul>
      </div>
    </div>
     <div class="card card-outline-primary" style="height: 150pt;" >
      <div class="card-header" style="height: 35pt;" >Most Viewed</div>
        <div class="card-block" style="height: 85pt;">
            <ul>
              {% for post in most_views_posts %}
                <li><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></li>
              {% endfor %}
           </ul>    
        </div>
    </div>
    <div class="card card-outline-primary" style="height: 150pt;" >
      <div class="card-header" style="height: 35pt;" >Letest Updated </div>
        <div class="card-block" style="height: 85pt;">
            <ul>
              {% for post in updated_posts %}
                <li><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></li>
              {% endfor %}
           </ul>    
        </div>
    </div>
    </div>
    </div>
    </div>
  {% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="post">
        <h2>{{ post.title }}</h2>
        <h6 class="text-muted" data-post_id="{{ post.id }}" id="post_title_id" data-api_post_comments_list_url="{% url 'post-comment-list' post.id  %}" data-api_post_detail_url="{% url 'post-detail' post.id %}">Author: {{ post.author|title }}.</h6>
        {% if post.published_date %}
            <div class="date">
                Published On : {{ post.published_date }}
            </div>
        {% endif %}
        <p>{{ post.text|linebreaksbr }}</p>
        <hr>
 
        {% if user.is_authenticated %}
            <div class="container-fluid">
                <form method="POST" action="." class="post-form" id="comment_form" data-comment_post_url="{% url 'post-detail' post.id %}" 
                data-api_post_create_url="{% url 'comment-create' %}">
                    {% csrf_token %}
                    {% include 'includes/form_snippet.html' %}
                    <input type="hidden" name="post" value="{{ post.id }}">
                    <button type="submit" class="save btn btn-primary">Comment</button>
                </form>
            </div>
            <h5>Latest comments</h5>
            <div class="container" id="post_comments" class="my-new-list"> </div>
        {% else %}
            <strong>To post comments <a href="{% url 'account_login' %}" >Login </a>
            or <a href="{% url 'account_signup' %}" >SignUp</a>. </strong>
            
        {% endif %}
    </div>
    {% include 'blog/includes/reply_modal.html' %}
{% endblock %}

blog/templates/blog/post_detail_comment.html
{% for comment in post.comments.all %}
	{% if comment.parent == None %}
	<div class="card card-outline-info comment" >
    	<div class="card-header date"> 
    	<strong class="card-title">{{ comment.author|title }}</strong> On {{ comment.created_date }} Replies: {{ comment.has_replies.count }}
    	</div>
    	<div class="card-block">
        	<div class="card-text" >
            	<p >{{ comment.text }}</p>
            	<button class="btn btn-primary btn-sm button-reply" type="button">reply	</button>
                <button class="btn btn-primary btn-sm button-view-replies" type="button">
            			Replies{{ comment.has_replies.count }}
            	</button>
            	<div >
                	<ul class="comment-replies" >
                		{% for replies in comment.has_replies %}
                			<li>By:{{ replies.author }} :- {{ replies.text }}</li>
                		{% empty %}
                			<li> No replies</li>
                		{% endfor %}
                	</ul>
            	</div>
            	<form method="POST" action="." class="form-inline form-replies" >{% csrf_token %} 
                    {% include 'includes/form_snippet.html' %}
                    <input type="hidden" name="parent_id" value='{{ comment.id }}'>
                    <button type="submit" class="save btn btn-success ml-2">Reply</button>
                </form>
        	</div>
    	</div>
	</div>
	{% endif %}
{% empty %}
	<p>No comments here yet :(</p>
{% endfor %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">

{% endblock %}
{% block content %}
<div class="conatiner">
    <div class="row">
        <div class=" col-sm-12">
            <h1>{{ title_text }}</h1>
            <form method="POST" class="post-form"  id="new_post_form">
                {% csrf_token %}
                {% include 'includes/form_snippet.html' %}
            <button type="submit" class="save btn btn-info">{{ btn_text }}</button>
            </form>
        </div>
        <!-- <div class="col-sm-6">
            <h1> Preview</h1>
            <h3 id="new_post_title">Post Title</h3>
            <h6 >Author : {{ user.username|title }}</h6>
            <h4 id="new_post_content">Post Content </h4>
        </div> -->
</div>
{% endblock %}
{% block javascript %}

    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
      <script>
        var simplemde = new SimpleMDE({ element: $("#MyID")[0] });
      </script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load tags %}


    {% block content %}
    {% if messages %}
        {% for messages in messages %}
        <div class="alert alert-danger " role="alert">    
            <strong>{{ messages }}</strong>  {{ post.title }}
        </div>
        {% endfor %}
    {% endif %}
    <div class="container-fluied ">
    <div class="row">
    <div class  ="col-md-8 ">
    <h1> Blog Posts </h1>  
    <div class="infinite-container">
    {% for post in posts %}
      <div class="infinite-item">
        <div class="card card-outline-primary"  >
          <div class="card-header " >
                <h5 class="card-title"><a href="{% url 'posts:post_detail' pk=post.pk %}">{{ post.title|title }}</a></h5> 
                <p><b>Pub On :</b> {{post.published_date|date }} <b>By :</b> {{ post.author|title }} <b>Comments :</b> {{ post.comments.count }} <b>Views :</b> {{ post.views }} <b>Likes :</b> {{ post.likes.count }} </p> 
          </div>
          <div class="card-block" >
              <p class="card-text" >{{ post.text|truncatewords:10}}</p>
              <a class="card-link btn" href="{% url 'posts:post_detail' pk=post.pk %}">Read more >></a>
            {% if user.is_authenticated and post.author == request.user %}
              <a class="card-link btn" href="{% url 'posts:post_edit' pk=post.pk %}"> Edit
              <a class="card-link btn" href="{% url 'posts:del_blog' pk=post.pk %}"> Delete</a>
            {% endif %}

              <a class="card-link btn like-btn" data-href="{% url 'posts:like-toggle' post.pk %}" data-likes='{{ post.likes.count }}' href='{{ post.get_like_url }}'>Like</a>
          </div>
        </div>
        </div>
    {% empty %}
      <strong>No posts found!</strong>
    {% endfor %}
   </div>
    <div class="loading" style="display: none;">
      Loading...
    </div>

    {% if page_obj.has_next %}
      <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">More</a>
    {% endif %}
    </div>   

    <div class="col-md-4">
      <div class="card card-outline-primary"  >
        <div class="card-header"  ><h4>Top Commented</h4></div>    
        <div class="card-block" >
             <ul>
                {% most_commented_posts %}
             </ul>
        </div>
      </div>
      <div class="card card-outline-primary">
        <div class="card-header"  ><h4>Most Viewed</h4></div>
          <div class="card-block" >
              <ul>
                {% most_viewed_posts %}
             </ul>    
          </div>
      </div>
      <div class="card card-outline-primary" >
        <div class="card-header" ><h4>Letest Updated</h4> </div>
          <div class="card-block">
              <ul>
                {% latest_added_posts %}
             </ul>    
          </div>
      </div>
    </div>
    </div>
    </div>
  {% endblock %}

  {% block javascript%}
    <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });
    </script>
  {% endblock %}

blog/templates/blog/user_list.html
{% extends 'base.html' %}

    {% block content %}
    <div class="container-fluid">
    <table class="table table-bordered">
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.email }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
    </div>
     {% endblock %}

blog/templates/blog/view_post.html
{% extends 'base.html' %}

{% block content %}

    <meta charset="UTF-8">
    <title>Ajax search</title>

<body>
    <div id="search_content">
        <form action="">
            {% csrf_token %}
            <input id="query" name="query" type="text" placeholder="Search..." />
        </form>
    </div>
    {% if post %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.content }}</p>
    {% endif %}
</body>

{% endblock %}
{% block javascript %}
        <script type="text/javascript" src="{% static 'js/livesearch.js' %}"></script>
{% endblock %}

blog/templates/blog/writer_request.html
{% extends 'base.html' %}

{% block content %}
    <h2> Contact Us </h2>
    <form method="POST" class="post-form " >
        {% csrf_token %}
        {% include 'includes/form_snippet.html' %}
    <button type="submit" class="save btn btn-info">Send Email</button>
    </form>
{% endblock %}