blog/urls.py
from django.conf.urls import url, include
from . import views



urlpatterns = [

    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/detail/$', views.PostDetailView.as_view(), name='post_detail'),
    # url(r'^like/$',views.post_like, name='like'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/del/$',views.PostDeleteView.as_view(),name='del_blog'),
    # url(r'^post/search_post/$', views.BlogSearchListView.as_view(), name='search_post'),
    # url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/new/$', views.PostCreateView.as_view(), name='post_new'),
    # url(r'^post/(?P<pk>\d+)/detail/$',views.post_detail, name='post_detail'),
    # url(r'^post/(?P<pk>\d+)/edit/$',views.post_edit,name='post_edit'),
    # url(r'^post/(?P<pk>\d+)/del/$',views.del_blog,name='del_blog'),
    url(r'^password/$', views.change_password, name='change_password'),
    # url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post_title/$',views.search_post_title, name = 'post_title'),  
    
    url(r'^(?P<pk>[\d]+)/like/$', views.PostLikeToggle.as_view(), name='like-toggle'),
    url(r'^api/(?P<pk>[\d]+)/like/$', views.PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    url(r'^request/$',views.WriterRequestForm.as_view(),name='writer_request'),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog import views
from accounts import views as accounts_views
from django.views.generic import TemplateView
from tastypie.api import Api
from blog.api import views as blog_views
from rest_framework.routers import DefaultRouter

# from blog.api import AjaxSearchResource
# router = DefaultRouter()
# router.register(r'post', PostViewSet)
# router.register(r'user', UserViewSet)

urlpatterns = [
    url(r'^login/$',auth_views.login,name='login'),
    url(r'^logout/$',auth_views.logout,name='logout'),
    # url(r'^signup/$',views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='posts')),
    url(r'^profiles/',include('accounts.urls',namespace='profiles')),
    # url(r'^api/',include(rest_api.urls)),
    url(r'^api/$', blog_views.api_root),
    url(r'^api/post/',include('blog.api.urls')),
    url(r'^api/users/',include('accounts.api.urls',namespace='api-users')),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^rest-auth/', include('rest_auth.urls',namespace='rest')),
    # url(r"^likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    # url(r'^auth/', include('rest_framework_social_oauth2.urls')),
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^about/$', views.AboutView.as_view(),name='about_us'),
    # url(r'^posts-api/', include(router.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls',namespace='pages')),
    url(r'^contact/$', views.ContactView.as_view(),name='contact'),
    url(r'^signup/$',accounts_views.signup, name='signup'),
    url(r'^ajax/validate_username/$',accounts_views.validate_username, name='validate_username'),
    url(r'^profile/$',accounts_views.MyProfileView.as_view(),name='my_profile'),
    url(r'^reset/$',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ),
    name='password_reset'),
    url(r'^reset/done/$',
    auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
    name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
    name='password_reset_confirm'),
    url(r'^reset/complete/$',
    auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    name='password_reset_complete'),

    url(r'^account_activation_sent/$', accounts_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        accounts_views.activate, name='activate'),


]

urlpatterns += [
    
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

templates/about_us.html
{% extends 'base.html' %}

{% block content %}
    <h1> About Us</h1>
{% endblock %}

templates/base.html
{% load static %}
{% load tags %}
{% load flatpages %}
{% get_flatpages as flatpages %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django blog</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        {% block stylesheets %}
        {% endblock %}
    </head>
    <body>
   
  <div class="container-fluied">
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse" >
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Django Blog's</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:post_list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        {% if user|has_group:"Writer" %}
        <a class="nav-link" href="{% url 'posts:post_new' %}">New Blog</a>
        {% endif %}
       </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
      </li>
      <li class="nav-item">
        {% for page in flatpages %}
        <a class="nav-link" href="{{ page.url }}">{{ page.title }}</a>
        {% endfor %}
      </li>
     
      <form class="form-inline ml-auto" action="{% url 'posts:post_list' %}" data-url="{% url 'posts:post_title' %}" id="form_search_post" >
      <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q" id="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="padding-right: 20px;">Search</button>
      </form>
      
      </ul>
        
      {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
         <li class="nav-item ">
        <div class="dropdown">
          <a class="nav-link dropdown-toggle"  data-toggle="dropdown">Messages
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="nav-item">
                <a href="{% url 'pinax_messages:inbox' %}"><i class="fa fa-envelope"></i> Message Inbox</a>
            </li>
            <li class="nav-item">
                 <a href="{% url 'pinax_messages:message_create' %}"><i class="fa fa-envelope"></i> New Message</a>
            </li>
           <!--  <li class="nav-item">
                <a href=""><i class="fa fa-envelope"></i> "View Message Thread" </a>
            </li> -->
          </ul>
        </div>
        </li>
        <li class="nav-item dropdown " >
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.username|title }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_profile' %}">MyAccount</a>
            {% if user|has_group:"Reader" %}
            <a class="dropdown-item" href="{% url 'posts:writer_request'%}">Request to be Writer.</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'posts:change_password' %}">Change Password</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            <!-- <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>
      </ul>
      {% else %}
      
      <form class="form-inline ml-auto" >
      
        <a class="btn btn-outline-info ml-5" href="{% url 'account_login' %}" role="button">Login</a>
        <a class="btn btn-outline-success ml-2" href="{% url 'account_signup' %}" role="button">Sign up</a>
      </form>
      
      {% endif %}
    
    
  </div>
</nav>
</div>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--     <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
 -->   
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/eldarion-ajax@0.16.0/js/eldarion-ajax.min.js"></script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
    <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script> -->
    <script src="{% static 'js/jquery.waypoints.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    {% block javascript%}
    {% endblock %}
    </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h2> Contact Us </h2>
    <form method="POST" class="post-form contact-form" data-url = "{% url 'contact' %}" >
        {% csrf_token %}
        {% include 'includes/form_snippet.html' %}
    <button type="submit" class="save btn btn-info">Send Email</button>
    </form>
{% endblock %}